import styles from '@/styles/disclaimer.module.css';
import React from 'react';
import 'bootstrap/dist/css/bootstrap.css';




function Disclaimer() {


    return (
        <>
            <div className={styles.disclaimer_box}>
                <h2>Disclaimer</h2>
                <div className={styles.disclaimer_content}>
                    Last Updated: 25.03.2024 <br /><br />
                    <strong>1. Introduction</strong><br />
                    Welcome to Turn It Green. The information provided on this website is for general informational
                    purposes only. By accessing or using our website, you acknowledge and agree to the terms of this
                    disclaimer.
                    <br /><br />
                    <strong>2. No Legal or Financial Advice</strong><br />
                    The content provided on this website, including articles, information, and any future ESG products, is
                    not intended to constitute legal, financial, or professional advice. We do not provide legal, financial,
                    or professional services, and the content on this website should not be considered a substitute for
                    such services. You should consult with qualified professionals for specific legal, financial, or
                    professional advice.
                    <br /><br />
                    <strong>3. Accuracy and Reliability</strong><br />
                    We strive to provide accurate and up-to-date information on our website. However, we do not
                    guarantee the accuracy, completeness, or reliability of the content. Information may change over
                    time, and we do not assume any responsibility for errors or omissions in the content.
                    <br /><br />
                    <strong>4. Third-Party Content</strong><br />
                    Our website may contain links to third-party websites or third-party content. We do not endorse or
                    control these third-party websites or their content. We are not responsible for the accuracy, legality,
                    or quality of third-party content, and we do not accept liability for any harm or damages that may
                    result from accessing or using such content.
                    <br /><br />
                    <strong>5. No Liability</strong><br />
                    To the fullest extent permitted by applicable law, we disclaim any liability for any direct, indirect,
                    incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether
                    incurred directly or indirectly, arising from your use of our website or the content provided on it.<br /><br />

                    <strong>6. AI Content Generation</strong><br />
                    This website employs artificial intelligence (AI) technology to assist in the generation of articles and
                    content related to ESG (Environmental, Social, and Governance) regulations. While AI plays a role in
                    the content creation process, it is essential to note the following:<br />
                    Human Review: Our editorial team reviews and edits all articles generated by AI to ensure accuracy,
                    quality, and compliance with our editorial standards.<br />
                    AI Assistance: AI is used to expedite the content creation process and provide timely and relevant
                    information to our readers. However, the final content is curated and verified by our team.<br />
                    Limited Liability: While we strive to provide accurate and up-to-date information, we do not
                    guarantee the accuracy, completeness, or reliability of the content. The information provided should
                    not be considered a substitute for professional advice.<br /><br />
                    <strong>7. Changes to Disclaimer</strong><br />
                    We may update this disclaimer from time to time to reflect changes in our practices, applicable laws,
                    or other operational reasons. We encourage you to review this disclaimer periodically to stay
                    informed about our policies and your responsibilities when using our website.<br /><br />

                    <strong>8. Contact Us</strong><br />
                    If you have any questions or concerns about this disclaimer or any other aspect of our website,
                    please contact us at office(at)turnitgreen.eu.
                </div>
            </div>

        </>
    );
}

export default Disclaimer;
